<?php

namespace FG\NewsBundle\Repository;

/**
 * ImageNewsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageNewsRepository extends \Doctrine\ORM\EntityRepository
{
}
