<?php

namespace FG\NewsBundle\Repository;

/**
 * NewsletterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NewsletterRepository extends \Doctrine\ORM\EntityRepository
{

	public function getFuturNews()
	{
		$datecourrante = new \DateTime;
		$qb = $this->createQueryBuilder('n');
		$qb
		->where ('n.date >= :date')
		->setParameter('date', $datecourrante)
		->orderBy('n.date','DESC');
		return $qb->getQuery()->getResult();

	}
}
