fg_news_homepage:
    path:     /
    defaults: { _controller: FGNewsBundle:Default:index }
fg_news_view:
    path:     /view/{id}
    defaults:
      _controller: FGNewsBundle:Default:index
    requirements:
      id: \d+  
fg_news_add:
    path:     /add
    defaults: { _controller: FGNewsBundle:Default:add }
fg_news_all:
    path:     /all
    defaults: { _controller: FGNewsBundle:Default:all }