fg_news_homepage:
    path:     /
    defaults: { _controller: FGNewsBundle:Default:index }
fg_news_view:
    path:     /view/{id}
    defaults:
      _controller: FGNewsBundle:Default:viewNews
    requirements:
      id: \d+  
fg_news_edit:
    path:     /edit/{id}
    defaults:
      _controller: FGNewsBundle:Default:index
    requirements:
      id: \d+
fg_news_delete:
    path:     /delete/{id}
    defaults:
      _controller: FGNewsBundle:Default:deleteNews
    requirements:
      id: \d+  
fg_news_add:
    path:     /add
    defaults: { _controller: FGNewsBundle:Default:add }
fg_news_futur:
    path:     /futur
    defaults: { _controller: FGNewsBundle:Default:futurNews }